### ISSUE TITLE
Can I chain non-Mux'd i2c devices off of a Mux'd device?

### ISSUE THREAD

**Issue by tig** [sparkfun/SparkFun_I2C_Mux_Arduino_Library#1]
See this pic:
![image](https://user-images.githubusercontent.com/585482/126604721-3c719e85-7708-49ea-bf33-f0f864918393.png)

Now, what if I plugged another i2c device into one of the ports on the device on the bottom-right (or top-left)? 

Would it all work? Or am I restricted to a single device connected to each Mux port?

**Comment by nseidle** [comment]
Short answer is yes, that's fine. You can have a daisychain of devices out any given port of the mux. Now just be sure all the devices on your chain don't have the same I2C address. If it does, just put it on a different port on the mux.

**Comment by tig** [comment]
Thanks. I asked because the devices weren't showing up with my scan code. I now see that the real problem is Qwiic Buttons and Relays struggle to be 'seen' when on the FAR end of a differential extender that is connected to a mux port on the Qwiic mux. I'll go to the forums to get help...
