### ISSUE TITLE
Same return value for 2 different cases in getPort()

### ISSUE THREAD

**Issue by 3sigma** [sparkfun/SparkFun_I2C_Mux_Arduino_Library#3]
Hello,

In getPort, this line:

https://github.com/sparkfun/SparkFun_I2C_Mux_Arduino_Library/blob/6a92d3e409f7a7053961e04fc37a5d95b7940a86/src/SparkFun_I2C_Mux_Arduino_Library.cpp#L88

returns the same value as this one:

https://github.com/sparkfun/SparkFun_I2C_Mux_Arduino_Library/blob/6a92d3e409f7a7053961e04fc37a5d95b7940a86/src/SparkFun_I2C_Mux_Arduino_Library.cpp#L79

So, when you get 255 from this function, you don't know if there is an error or if you only didn't set a port.

Thanks,

Nicolas

**Comment by nseidle** [comment]
Agreed. I didn't set that up very well. Would returning 254 for error be sufficient? I think so.

**Comment by 3sigma** [comment]
Yes, I have no better suggestion.

**Comment by nseidle** [comment]
Fixed in v1.0.3
